openapi: 3.0.1
info:
  title: CorpusExplorer REST-WebService
  termsOfService: 'https://www.gnu.org/licenses/agpl-3.0.de.html'
  contact:
    name: Jan Oliver Rüdiger
    url: 'https://notes.jan-oliver-ruediger.de/kontakt/'
  license:
    name: GNU Affero General Public License 3.0
    url: 'https://www.gnu.org/licenses/agpl-3.0.de.html'
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:9999'
paths:
  /execute/:
    post:
      description: Executes a command against a corpus (defined by corpusId)
      parameters:
        - name: request
          in: query
          description: Executes a command against the complete corpus or a sub-corpus (defined by GUIDs)
          required: true
          schema:
            type: object
            properties:
              action:
                type: string
              arguments:
                type: object
                additionalProperties:
                  type: string
              corpusId:
                type: string
      responses:
        '200':
          description: execution result
  /add/langauges/:
    get:
      description: 'lists all available languages for http://127.0.0.1:9999/add/'
      responses:
        '200':
          description: all available languages
  /add/:
    post:
      description: Adds/analyzes a new corpus
      parameters:
        - name: request
          in: query
          description: Adds/analyzes a new corpus
          required: true
          schema:
            type: object
            properties:
              language:
                type: string
                description: see /add/language/ for all available languages.
              documents:
                type: array
                items:
                  type: object
                  properties:
                    text:
                      type: string
                    metadata:
                      type: object
                      additionalProperties:
                        type: string
      responses:
        '200':
          description: corpusId
  /execute/actions/:
    get:
      description: 'Lists all available actions for http://127.0.0.1:9999/execute/'
      responses:
        '200':
          description: action = The name of the action / description = Short description - action and parameter
